name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (flake8)
        run: |
          python -m flake8

      - name: Tests
        env:
          DJANGO_SECRET_KEY: "ci-secret"
          DJANGO_DEBUG: "false"
          SENTRY_ENABLE: "false"
        run: |
          python manage.py test
